#!/bin/bash
./random-pop-generator -i AraripeManakin.txt.db -n 5 -r 100
./random-pop-generator -i AraripeManakin.txt.db -n 10 -r 100
./random-pop-generator -i AraripeManakin.txt.db -n 15 -r 100
./random-pop-generator -i AraripeManakin.txt.db -n 20 -r 100
./random-pop-generator -i AraripeManakin.txt.db -n 25 -r 100
./random-pop-generator -i AraripeManakin.txt.db -n 30 -r 100
./random-pop-generator -i AraripeManakin.txt.db -n 35 -r 100
./random-pop-generator -i AraripeManakin.txt.db -n 40 -r 100
./random-pop-generator -i AraripeManakin.txt.db -n 45 -r 100
./random-pop-generator -i AraripeManakin.txt.db -n 50 -r 100
./random-pop-generator -i AraripeManakin.txt.db -n 55 -r 100
./random-pop-generator -i AraripeManakin.txt.db -n 60 -r 100
./random-pop-generator -i AraripeManakin.txt.db -n 65 -r 100
./random-pop-generator -i AraripeManakin.txt.db -n 70 -r 100
./random-pop-generator -i AraripeManakin.txt.db -n 75 -r 100
./random-pop-generator -i AraripeManakin.txt.db -n 80 -r 100
./random-pop-generator -i AraripeManakin.txt.db -n 85 -r 100
./random-pop-generator -i AraripeManakin.txt.db -n 90 -r 100
./random-pop-generator -i AraripeManakin.txt.db -n 95 -r 100
./random-pop-generator -i AraripeManakin.txt.db -n 100 -r 100
