#!/bin/bash
w=$(tput sgr0) 
r=$(tput setaf 1)
g=$(tput setaf 2) 
y=$(tput setaf 3) 
home_dir=$(echo ~/)
	echo "${g}"
	echo	"________________________________________________________________________________"
	echo 	""
	echo    "______________________________ Seqs-Extractor 1.0 ______________________________"
	echo	"________________________________________________________________________________"
	echo	""
	echo "${w}"
	echo    "--------------------------------------------------------------------------------"
	echo    "                             Working directory                                  "
	echo    "--------------------------------------------------------------------------------"
		echo ""
	echo "What is the directory that you are working, Leave blank to use default"
	echo "${y}NOTE: Default is your Home folder($home_dir)${w}"
		echo "${g}"
		read work_dir
		echo "${w}"

if [ ! -d $work_dir ];
then
echo "${r}"
while 
read -p 'Try again: ' work_dir && [ ! -d $work_dir ]; do
echo "${r}
-------------------------------------------------------------
ERROR ${w}$work_dir${r} IS NOT A VALID DIRECTORY, PLEASE CHOOSE A VALID FOLDER!
-------------------------------------------------------------
"
done
fi

cd $work_dir
if [ $? -eq 0 ]
then
clear
else
echo "${r}
-------------------------------------------------------------------------------------------
ERROR ${w}$work_dir${r} 
IS NOT A VALID DIRECTORY, PLEASE CHOOSE A VALID FOLDER AND TRY RUN THE Seqs-Extractor AGAIN,
THIS COMMONLY OCCURS BECAUSE YOU ARE TRYING USE AND INVALID FOLDER OR A DIRECTORY THAT
CONTAINS SPACES.
${y}Example /home/lbn/teste dois/${r}
THE FOLDER NAMES CAN NOT CONTAIN SPACES, YOU CAN REPLACE SPACES BY UNDERLINE 
${y}Example /home/lbn/teste_dois/${r}
-------------------------------------------------------------------------------------------
"
function pause(){
   read -p "$*"
}
echo -e "setf 4" | tput -S
pause 'Press [Enter] key to finish the script and this terminal window!'
exit 1
fi

if [[ -z "$work_dir" ]]
then
selected_dir="$home_dir"
else
selected_dir="$echo $work_dir"
fi

						# EXTRACTION FROM MISA FILE

clear
echo "${g}"
echo	"________________________________________________________________________________"
echo 	""
echo    "______________________________ Seqs-Extractor 1.0 ______________________________"
echo	"________________________________________________________________________________"
echo	""
echo	"${y}NOTE: Your work directory is${w} $selected_dir${g}"
echo "${w}"
		echo    "--------------------------------------------------------------------------------"
		echo    "			       Fasta to compare 				 "
		echo    "--------------------------------------------------------------------------------"
			echo ""
		echo "Enter the name of fasta file to run:"	
		echo 	"${g}"
			read fastafile
		echo ""

if [ -f $fastafile ];
then
echo "Fasta file is ok!"
else
while 
read  -p 'Error File not found, Try again: ' fastafile && [ ! -f $fastafile ] ; do
echo "${r}
--------------------------------------------------------------------------
THE FILE ${w}$fastafile${r} NOT FOUND, VERIFY IF THE NAME OR PATH TO FILE IS CORRECT!
YOU TYPED ""${w}$fastafile${r}""
--------------------------------------------------------------------------
"
done
fi
		clear
echo "${g}"
echo	"________________________________________________________________________________"
echo 	""
echo    "______________________________ Seqs-Extractor 1.0 ______________________________"
echo	"________________________________________________________________________________"
echo	""
echo	"${y}NOTE: Your work directory is${w} $selected_dir${g}"
echo "${w}"
		echo    "--------------------------------------------------------------------------------"
		echo    "    			     MISA results       "
		echo    "--------------------------------------------------------------------------------"
			echo ""
		echo "Enter the name of file containing the MISA results(example.fasta.misa)"
		echo "${g}"
			read misa_results_file
		echo ""

if [ -f $misa_results_file ];
then
echo "Fasta file is ok!"
else
while 
read  -p 'Error File not found, Try again: ' misa_results_file && [ ! -f $misa_results_file ] ; do
echo "${r}
--------------------------------------------------------------------------
THE FILE ${w}$misa_results_file${r} NOT FOUND, VERIFY IF THE NAME OR PATH TO FILE IS CORRECT!
YOU TYPED ""${w}$misa_results_file${r}""
--------------------------------------------------------------------------
"
done
fi

#Change the entire path to only last name
pathname=$fastafile
echo $(basename $pathname) > .fastafile_name.txt
fastafile_name=`cat .fastafile_name.txt`

pathname=$misa_results_file 
echo $(basename $misa_results_file ) > .misa_results_file_name.txt
misa_results_file_name=`cat .misa_results_file_name.txt`


#Replace spaces by underline in the fasta file
sed 's/ /_/g' $fastafile_name > .$fastafile_name

#Replace spaces by underline
sed 's/ /_/g' $misa_results_file_name > .$misa_results_file_name

#extracts only the first colum thats contains the IDs
cut -f1 .$misa_results_file_name > .temp0
rm -rf .$misa_results_file_name
#Romove first line
sed '1d' .temp0 > .temp1			
rm -rf .temp0
#Remove duplicated IDs
sort -u .temp1 > .temp2
rm -rf .temp1
#add > in the start
sed 's/^/>/' .temp2 > .temp3
rm -rf .temp2

#Romove first line empty
sed '1d' .temp3 > .temp4
rm -rf .temp3


if			
				echo "${w}"
				echo    "------------------------------------------------------------------"
				echo	"Extracting sequences, just wait.			 	   "
				echo 	"This may take a while and depends on the size of your database."
				echo    "------------------------------------------------------------------"
				echo	""
	
#function of slash spin
spinner()
{
    local pid=$1
    local delay=0.75
    local spinstr='|/-\'
    while [ "$(ps a | awk '{print $1}' | grep $pid)" ]; do
        local temp=${spinstr#?}
        printf " [%c]  " "$spinstr"
        local spinstr=$temp${spinstr%"$temp"}
        sleep $delay
        printf "\b\b\b\b\b\b"
    done
    printf "    \b\b\b\b"
}

( cut -c 2- .temp4 | xargs -n 1 samtools faidx .$fastafile_name > $fastafile_name.MISA_extracted_seqs.fasta ) &
echo -n "Running SAMTOOLS, please wait... "
spinner $!
echo " DONE!"
then
				echo "${g}"
				echo    "--------------------------------------------------------------------------------"
				echo	"		 	 Sequences successfully extracted!!!			 "
				echo    "--------------------------------------------------------------------------------"
				echo	""
else
						echo -e "setf 4" | tput -S  # set fg red
						echo	"ERROR!"
						echo	"PLEASE VERIFY IF THE COMMANDS AND NAME OF FILES ARE CORRECT!!!!"
						function pause(){
						read -p "$*"
						}
						echo -e "setf 4" | tput -S
						pause 'Press [Enter] key to finish the script'
						exit 1
					fi
			
rm -rf .temp4 .fastafile_name.txt .misa_results_file_name.txt .$fastafile_name.fai .temp4 .fastafile_name.txt .$fastafile_name .$misa_results_file_name .misa_results_file_name.txt



if [ -s $fastafile_name.MISA_extracted_seqs.fasta ] 
then

    
echo -e "setf 8" | tput -S  # set fg green
echo	"================================================================================"
echo 	""
echo    "============================ Seqs-Extractor 1.0 ================================"
echo 	""
echo	"================================================================================"
echo    "============= Laboratório de Biologia Molecular e Neuroecologia ================"
echo	'============== INSTITUTO FEDERAL DO PARÁ (IFPA) Campus Bragança ================'
echo	"================================================================================"
echo '				 ___        ______    __     __
				|   |      |	  \  |  \   |  | 
				|   |      |   D   ) |   \  |  | 
				|   |      |      /  |    \ |  | 
				|   |____  |      \  |  |\ \|  | 
				|        | |   D   ) |  | \    |  
				|________| |______/  |__|  \___|
'                     
echo	"All commands completed successfully"
echo	":D"
echo	"Support by E-mail to patrick@ufpa.br"
echo	""
echo    "--------------------------------------------------------------------------------"
echo	"The extracted sequences are written in${w} $fastafile_name.MISA_extracted_seqs.fasta${g}" 
echo    "${y}NOTE: Results are available at${w} $selected_dir${g}"
echo    "--------------------------------------------------------------------------------"


else
clear
echo "${r}"
	echo    "-------------------------------------------------------------------------------------------
"
	echo	"No sequences was found in $misa_results_file, please verify if $misa_results_file are in the MISA format!
	"
	echo    "-------------------------------------------------------------------------------------------"
	echo	""

rm -rf .temp4 .fastafile_name.txt .misa_results_file_name.txt .$fastafile_name.fai .temp4 .fastafile_name.txt .$fastafile_name .$misa_results_file_name .misa_results_file_name.txt $fastafile_name.MISA_extracted_seqs.fasta 
fi
