#!/bin/bash
w=$(tput sgr0) 
r=$(tput setaf 1)
g=$(tput setaf 2) 
y=$(tput setaf 3) 
home_dir=$(echo ~/)
	echo "${g}"
	echo	"________________________________________________________________________________"
	echo 	""
	echo    "______________________________ Seqs-Extractor 1.0 ______________________________"
	echo	"________________________________________________________________________________"
	echo	""
	echo "${w}"
	echo    "--------------------------------------------------------------------------------"
	echo    "                             Working directory                                  "
	echo    "--------------------------------------------------------------------------------"
		echo ""
	echo "What is the directory that you are working, Leave blank to use default"
	echo "${y}NOTE: Default is your Home folder($home_dir)${w}"
		echo "${g}"
		read work_dir
		echo "${w}"

if [ ! -d $work_dir ];
then
echo "${r}"
while 
read -p 'Try again: ' work_dir && [ ! -d $work_dir ]; do
echo "${r}
-------------------------------------------------------------
ERROR ${w}$work_dir${r} IS NOT A VALID DIRECTORY, PLEASE CHOOSE A VALID FOLDER!
-------------------------------------------------------------
"
done
fi

cd $work_dir
if [ $? -eq 0 ]
then
clear
else
echo "${r}
-------------------------------------------------------------------------------------------
ERROR ${w}$work_dir${r} 
IS NOT A VALID DIRECTORY, PLEASE CHOOSE A VALID FOLDER AND TRY RUN THE Seqs-Extractor AGAIN,
THIS COMMONLY OCCURS BECAUSE YOU ARE TRYING USE AND INVALID FOLDER OR A DIRECTORY THAT
CONTAINS SPACES.
${y}Example /home/lbn/teste dois/${r}
THE FOLDER NAMES CAN NOT CONTAIN SPACES, YOU CAN REPLACE SPACES BY UNDERLINE 
${y}Example /home/lbn/teste_dois/${r}
-------------------------------------------------------------------------------------------
"
function pause(){
   read -p "$*"
}
echo -e "setf 4" | tput -S
pause 'Press [Enter] key to finish the script and this terminal window!'
exit 1
fi

if [[ -z "$work_dir" ]]
then
selected_dir="$home_dir"
else
selected_dir="$echo $work_dir"
fi

					# RUN MISA AND PERFORM SEQUENCES EXTRACTION

clear
echo "${g}"
echo	"________________________________________________________________________________"
echo 	""
echo    "______________________________ Seqs-Extractor 1.0 ______________________________"
echo	"________________________________________________________________________________"
echo	""
echo	"${y}NOTE: Your work directory is${w} $selected_dir${g}"
echo "${w}"
		echo    "--------------------------------------------------------------------------------"
		echo    "			       Fasta to compare 				 "
		echo    "--------------------------------------------------------------------------------"
			echo ""
		echo "Enter the name of fasta file to run:"	
		echo 	"${g}"
			read fastafile
		echo ""

if [ -f $fastafile ];
then
echo "Fasta file is ok!"
else
while 
read  -p 'Error File not found, Try again: ' fastafile && [ ! -f $fastafile ] ; do
echo "${r}
--------------------------------------------------------------------------
THE FILE ${w}$fastafile${r} NOT FOUND, VERIFY IF THE NAME OR PATH TO FILE IS CORRECT!
YOU TYPED ""${w}$fastafile${r}""
--------------------------------------------------------------------------
"
done
fi
clear

cp  /usr/local/sbin/misa.pl misa.pl
chmod +x misa.pl

if [ -f misa.ini ];
then
echo "${w}"
echo    "------------------------------------------------------------------"
echo	"Running MISA in the file${g} $fastafile${w}."
echo 	"This may take a while and depends on the size of your database."
echo	"${y}NOTE: You are using a custom MISA parameters${w}"
echo    "------------------------------------------------------------------"
echo	""	
mkdir -p misa.ini.custom
cp misa.ini misa.ini.custom/misa.ini

else
cp /usr/local/sbin/seqs-extractor/misa.ini misa.ini

echo "${w}"
echo    "------------------------------------------------------------------"
echo	"Running MISA in the file${g} $fastafile${w}."
echo 	"This may take a while and depends on the size of your database."
echo	"${y}NOTE: You are using default MISA parameters${w}"
echo    "------------------------------------------------------------------"
echo	" "
fi

#Run MISA

spinner()
{
    local pid=$1
    local delay=0.75
    local spinstr='|/-\'
    while [ "$(ps a | awk '{print $1}' | grep $pid)" ]; do
        local temp=${spinstr#?}
        printf " [%c]  " "$spinstr"
        local spinstr=$temp${spinstr%"$temp"}
        sleep $delay
        printf "\b\b\b\b\b\b"
    done
    printf "    \b\b\b\b"
}

( ./misa.pl $fastafile misa.ini ) &
echo -n "Runing MISA, please wait... "
spinner $!
echo " DONE!"

#Change the entire path to only last name
pathname=$fastafile
echo $(basename $pathname) > .fastafile_name.txt
fastafile_name=`cat .fastafile_name.txt`
rm -rf .fastafile_name.txt

#Replace spaces by underline in the fasta file
sed 's/ /_/g' $fastafile_name > .temp0

#replace ' by #
sed "s/'/#/g" .temp0 > .$fastafile_name 
rm -rf .temp0


#Replace spaces by underline
sed 's/ /_/g' $fastafile_name.misa > .misa_results_file_name

#extracts only the first colum thats contains the IDs
cut -f1 .misa_results_file_name > .temp0
rm -rf .misa_results_file_name

#Remove first line
sed '1d' .temp0 > .temp1			
rm -rf .temp0
#Remove duplicated IDs
sort -u .temp1 > .temp2
rm -rf .temp1

#replace ' by #
sed "s/'/#/g" .temp2 > .temp3
rm -rf .temp2

#add > in the start
sed 's/^/>/' .temp3 > .temp4
rm -rf .temp3

#Remove first line empty
#sed '1d' .temp3 > .temp4
#rm -rf .temp3


if			
				echo "${w}"
				echo    "------------------------------------------------------------------"
				echo	"Extracting sequences, just wait.			 	   "
				echo 	"This may take a while and depends on the size of your database."
				echo    "------------------------------------------------------------------"
				echo	""
	
#function of slash spin
spinner()
{
    local pid=$1
    local delay=0.75
    local spinstr='|/-\'
    while [ "$(ps a | awk '{print $1}' | grep $pid)" ]; do
        local temp=${spinstr#?}
        printf " [%c]  " "$spinstr"
        local spinstr=$temp${spinstr%"$temp"}
        sleep $delay
        printf "\b\b\b\b\b\b"
    done
    printf "    \b\b\b\b"
}

( cut -c 2- .temp4 | xargs -n 1 samtools faidx .$fastafile_name > $fastafile_name.MISA_extracted_seqs.fasta ) &
echo -n "Running SAMTOOLS, please wait... "
spinner $!
echo " DONE!"
then

#replace # by '
sed "s/#/'/g" $fastafile_name.MISA_extracted_seqs.fasta > $fastafile_name.MISA_extracted_seqs.fasta.tmp 
rm -rf $fastafile_name.MISA_extracted_seqs.fasta
cat $fastafile_name.MISA_extracted_seqs.fasta.tmp > $fastafile_name.MISA_extracted_seqs.fasta
rm -rf $fastafile_name.MISA_extracted_seqs.fasta.tmp

				echo "${g}"
				echo    "--------------------------------------------------------------------------------"
				echo	"		 	 Sequences successfully extracted!!!			 "
				echo    "--------------------------------------------------------------------------------"
				echo	""
else
						echo -e "setf 4" | tput -S  # set fg red
						echo	"ERROR!"
						echo	"PLEASE VERIFY IF THE COMMANDS AND NAME OF FILES ARE CORRECT!!!!"
						function pause(){
						read -p "$*"
						}
						echo -e "setf 4" | tput -S
						pause 'Press [Enter] key to finish the script'
						exit 1
					fi
		

rm -rf .$fastafile_name .$fastafile_name.fai misa.ini misa.pl .temp4

if [ -s $fastafile_name.MISA_extracted_seqs.fasta ] 
then

    
echo -e "setf 8" | tput -S  # set fg green
echo	"================================================================================"
echo 	""
echo    "============================ Seqs-Extractor 1.0 ================================"
echo 	""
echo	"================================================================================"
echo    "============= Laboratório de Biologia Molecular e Neuroecologia ================"
echo	'============== INSTITUTO FEDERAL DO PARÁ (IFPA) Campus Bragança ================'
echo	"================================================================================"
echo '				 ___        ______    __     __
				|   |      |	  \  |  \   |  | 
				|   |      |   D   ) |   \  |  | 
				|   |      |      /  |    \ |  | 
				|   |____  |      \  |  |\ \|  | 
				|        | |   D   ) |  | \    |  
				|________| |______/  |__|  \___|
'                     
echo	"All commands completed successfully"
echo	":D"
echo	"Support by E-mail to patrick@ufpa.br"
echo	""
echo    "-------------------------------------------------------------------------------------------"
echo	"The extracted sequences are written in${w} $fastafile_name.MISA_extracted_seqs.fasta${g}"
echo    "MISA results are written in${w} $fastafile_name.misa${g} and${w} $fastafile_name.statistics${g}"
echo    "${y}NOTE: Results are available at${w} $selected_dir${g}"
echo    "-------------------------------------------------------------------------------------------"


else
clear
echo "${r}"
	echo    "-------------------------------------------------------------------------------------------
"
	echo	"No sequences was found in $misa_results_file, please verify if $misa_results_file are in the MISA format!
	"
	echo    "-------------------------------------------------------------------------------------------"
	echo	""

rm -rf .temp4 .$fastafile_name .$fastafile_name.fai misa.ini misa.pl 
fi
