#!/bin/bash
w=$(tput sgr0) 
r=$(tput setaf 1)
g=$(tput setaf 2) 
y=$(tput setaf 3) 
home_dir=$(echo ~/)
	echo "${g}"
	echo	"________________________________________________________________________________"
	echo 	""
	echo    "______________________________ Seqs-Extractor 1.0 ______________________________"
	echo	"________________________________________________________________________________"
	echo	""
	echo "${w}"
	echo    "--------------------------------------------------------------------------------"
	echo    "                             Working directory                                  "
	echo    "--------------------------------------------------------------------------------"
		echo ""
	echo "What is the directory that you are working, Leave blank to use default"
	echo "${y}NOTE: Default is your Home folder($home_dir)${w}"
		echo "${g}"
		read work_dir
		echo "${w}"

if [ ! -d $work_dir ];
then
echo "${r}"
while 
read -p 'Try again: ' work_dir && [ ! -d $work_dir ]; do
echo "${r}
-------------------------------------------------------------
ERROR ${w}$work_dir${r} IS NOT A VALID DIRECTORY, PLEASE CHOOSE A VALID FOLDER!
-------------------------------------------------------------
"
done
fi

cd $work_dir
if [ $? -eq 0 ]
then
clear
else
echo "${r}
-------------------------------------------------------------------------------------------
ERROR ${w}$work_dir${r} 
IS NOT A VALID DIRECTORY, PLEASE CHOOSE A VALID FOLDER AND TRY RUN THE Seqs-Extractor AGAIN,
THIS COMMONLY OCCURS BECAUSE YOU ARE TRYING USE AND INVALID FOLDER OR A DIRECTORY THAT
CONTAINS SPACES.
${y}Example /home/lbn/teste dois/${r}
THE FOLDER NAMES CAN NOT CONTAIN SPACES, YOU CAN REPLACE SPACES BY UNDERLINE 
${y}Example /home/lbn/teste_dois/${r}
-------------------------------------------------------------------------------------------
"
function pause(){
   read -p "$*"
}
echo -e "setf 4" | tput -S
pause 'Press [Enter] key to finish the script and this terminal window!'
exit 1
fi

if [[ -z "$work_dir" ]]
then
selected_dir="$home_dir"
else
selected_dir="$echo $work_dir"
fi
						# EXTRACTION FROM ANY TEXT FILE
clear


echo "${g}"
echo	"________________________________________________________________________________"
echo 	""
echo    "______________________________ Seqs-Extractor 1.0 ______________________________"
echo	"________________________________________________________________________________"
echo	""
echo	"${y}NOTE: Your work directory is${w} $selected_dir${g}"
echo "${w}"
		echo    "--------------------------------------------------------------------------------"
		echo    "			       Fasta to compare 				 "
		echo    "--------------------------------------------------------------------------------"
			echo ""
		echo "Enter the name of fasta file to run:"	
		echo 	"${g}"
			read fastafile
		echo ""

if [ -f $fastafile ];
then
echo "Fasta file is ok!"
else
while 
read  -p 'Error File not found, Try again: ' fastafile && [ ! -f $fastafile ] ; do
echo "${r}
--------------------------------------------------------------------------
THE FILE ${w}$fastafile${r} NOT FOUND, VERIFY IF THE NAME OR PATH TO FILE IS CORRECT!
YOU TYPED ""${w}$fastafile${r}""
--------------------------------------------------------------------------
"
done
fi

		clear
echo "${g}"
echo	"________________________________________________________________________________"
echo 	""
echo    "______________________________ Seqs-Extractor 1.0 ______________________________"
echo	"________________________________________________________________________________"
echo	""
echo	"${y}NOTE: Your work directory is${w} $selected_dir${g}"
echo "${w}"
		echo    "--------------------------------------------------------------------------------"
		echo    " 		   Text file containing a list of seqs IDS  		 		 "
		echo    "--------------------------------------------------------------------------------"
			echo ""
		echo "Enter the text file containing list of sequences that you want extract "
		echo "${g}"
			read list_file
		echo ""

if [ -f $list_file ];
then
echo "List file is ok!"
else
while 
read  -p 'Error File not found, Try again: ' list_file && [ ! -f $list_file ] ; do
echo "${r}
--------------------------------------------------------------------------
THE FILE ${w}$list_file${r} NOT FOUND, VERIFY IF THE NAME OR PATH TO FILE IS CORRECT!
YOU TYPED ""${w}$list_file${r}""
--------------------------------------------------------------------------
"
done
fi
clear

		if 
				if			
				echo "${w}"
				echo    "--------------------------------------------------------------------------------"
				echo	"Extracting sequences, just wait.			 "
				echo 	"This may take a while and depends on the size of your database. 	 "
				echo    "--------------------------------------------------------------------------------"

				echo	""
#Change the entire path to only last name
pathname=$list_file
echo $(basename $pathname) > .list_file_name.txt
list_file_name=`cat .list_file_name.txt`

#Change the entire path to only last name
pathname=$fastafile
echo $(basename $pathname) > .fastafile_name.txt
fastafile_name=`cat .fastafile_name.txt`
#Replace spaces by underline
sed 's/ /_/g' $fastafile > .$fastafile

#Replace spaces by underline
sed 's/ /_/g' $list_file > .$list_file

#function of slash spin
spinner()
{
    local pid=$1
    local delay=0.75
    local spinstr='|/-\'
    while [ "$(ps a | awk '{print $1}' | grep $pid)" ]; do
        local temp=${spinstr#?}
        printf " [%c]  " "$spinstr"
        local spinstr=$temp${spinstr%"$temp"}
        sleep $delay
        printf "\b\b\b\b\b\b"
    done
    printf "    \b\b\b\b"
}
( cut -c 2- .$list_file | xargs -n 1 samtools faidx .$fastafile > $list_file_name.$fastafile_name.extracted_seqs.fasta ) &
echo -n "Running SAMTOOLS, please wait... "
spinner $!
echo " DONE!"
					then
						echo " "
					else
						echo -e "setf 4" | tput -S  # set fg red
						echo	"ERROR!"
						echo	"PLEASE VERIFY IF THE COMMANDS AND NAME OF fiLES ARE CORRECT!!!!"
						function pause(){
						read -p "$*"
						}
						echo -e "setf 4" | tput -S
						pause 'Press [Enter] key to finish the script'
						exit 1
					fi
			then 
				echo "${g}"
				echo    "--------------------------------------------------------------------------------"
				echo	"		 	 Sequences successfully extracted!!!			 "
				echo    "--------------------------------------------------------------------------------"
				echo	""
rm -rf .fastafile_name.txt .list_file_name.txt
		fi			

if	
	rm .$fastafile
	rm .$list_file

then	
		echo "${g}"
	echo    "--------------------------------------------------------------------------------"
	echo	"			Temporary files successfully deleted!!!			 "
	echo    "--------------------------------------------------------------------------------"
	echo	""
	echo	""
	
else
	echo -e "setf 4" | tput -S  # set fg red
	echo	"ERROR WHILE TRY DELETE TEMPORARY fiLES!"
	
fi

#Replace underline by spaces
sed 's/_/ /g' $list_file_name.$fastafile_name.extracted_seqs.fasta > .1
rm -rf $list_file_name.$fastafile_name.extracted_seqs.fasta
sed -e '/len/ s/ /_/' .1 > .2
sed -e '/len/ s/ /_/' .2 > .3
sed -e '/len/ s/ /_/' .3 > .4
sed -e '/len/ s/ /_/' .4 > $list_file_name.$fastafile_name.extracted_seqs.fasta
rm -rf .1 .2 .3 .4


PATTERN=TRINITY_DN
FILE=$list_file_name.$fastafile_name.extracted_seqs.fasta
if grep -q $PATTERN $FILE;
 then
     echo ""
 else
sed 's/ /_/g' $list_file_name.$fastafile_name.extracted_seqs.fasta > .sed_tmp
rm -rf $list_file_name.$fastafile_name.extracted_seqs.fasta
cat .sed_tmp > $list_file_name.$fastafile_name.extracted_seqs.fasta
rm -rf .sed_tmp
fi

if [ -s $list_file_name.$fastafile_name.extracted_seqs.fasta ] 
then


    
echo -e "setf 8" | tput -S  # set fg green
echo	"================================================================================"
echo 	""
echo    "============================ Seqs-Extractor 1.0 ================================"
echo 	""
echo	"================================================================================"
echo    "============= Laboratório de Biologia Molecular e Neuroecologia ================"
echo	'============== INSTITUTO FEDERAL DO PARÁ (IFPA) Campus Bragança ================'
echo	"================================================================================"
echo '				 ___        ______    __     __
				|   |      |	  \  |  \   |  | 
				|   |      |   D   ) |   \  |  | 
				|   |      |      /  |    \ |  | 
				|   |____  |      \  |  |\ \|  | 
				|        | |   D   ) |  | \    |  
				|________| |______/  |__|  \___|
'                     
echo	"All commands completed successfully"
echo	":D"
echo	"Support by E-mail to patrick@ufpa.br"
echo	""
echo    "--------------------------------------------------------------------------------"
echo	"The extracted sequences are written in${w} $list_file_name.$fastafile_name.extracted_seqs.fasta${g}"    
echo    "${y}NOTE: Results are available at${w} $selected_dir${g}"
echo    "--------------------------------------------------------------------------------"
else
clear
     		echo "${r}"
	echo    "-------------------------------------------------------------------------------------------
"
	echo	"No sequences with $pct_ident% was found, please try again by changing your search criteria!
	"
	echo    "-------------------------------------------------------------------------------------------"
	echo	""

fi
