#!/bin/bash
w=$(tput sgr0) 
r=$(tput setaf 1)
g=$(tput setaf 2) 
y=$(tput setaf 3) 
S=`basename $0`
cpu=`nproc`
USAGE=`echo "USAGE:
${g}Example:${w} $S -i query.fa -o /home/user/test -b n -d mouse.preformated.blastdb.fa -p 90-100 -e 1e-20 -t 10 -a '-max_target_seqs 1'

Required arguments: 
-i <string> | Query fasta
-o <string> | Output directory
-b <n/x>    | Blast+ algorithm (n or x) 
-d <string  | Pre-formated Blast+ database
-p <string  | Pct. of identity to_extract Sequences

Optional arguments: 
-b <string>     | Default 1e-3 
-t <interger>   | Default: $cpu
-a <string>     | Blast+ optional parameters. E.g. '-max_target_seqs 1 -import_search_strategy filename' (Use between quotes!)"`

if [ "$#" -lt "1" ] 
then 
    echo $USAGE;
exit 1    
else 
    var1=$2;
    var2=$4;
fi

while getopts i:o:d:b:e:t:a:p: option
do
case "${option}"
in
i) query_fasta=${OPTARG};;
o) output_dir=$OPTARG;;
b) BLAST=$OPTARG;;
d) BLASTdb=$OPTARG;;
p) pct_ident=$OPTARG;;
e) BLAST_evalue=$OPTARG;;
t) threads=$OPTARG;;
a) other_blast_param=$OPTARG;;
esac
done
if [ "$query_fasta" = "" ]; then
"${g}Error, missing arguments:${y} -i | Trinity.fasta | <string>
${w}$USAGE"
exit 1
fi
if [ "$output_dir" = "" ]; then
"${g}Error, missing arguments:${y} -o | Output directory for extracted seqs | <string>
${w}$USAGE"
exit 1
fi
if [ "$BLAST" = "" ]; then
"${g}Error, missing arguments:${y} -b <n/x>    | Blast+ algorithm (n or x)
${w}$USAGE"
exit 1
fi
if [ "$BLASTdb" = "" ]; then
"${g}Error, missing arguments:${y} -d <string  | Pre-formated Blast+ database
${w}$USAGE"
exit 1
fi
if [ "$pct_ident" = "" ]; then
"${g}Error, missing arguments:${y} -p <string  | Pct. of identity to_extract Sequences
${w}$USAGE"
exit 1
fi
	echo "${g}"
	echo	"________________________________________________________________________________"
	echo 	""
	echo    "_______________________________ SeqsExtractor __________________________________"
	echo	"________________________________________________________________________________"
	echo	""
	echo "${g}"
	echo    "---------------------------------"
	echo    "Output directory"
	echo    "---------------------------------${w}"
echo "$output_dir ${g}"

if [ ! -d $output_dir ];
then
echo "${r}"
while 
read -p 'Try again: ' output_dir && [ ! -d $output_dir ]; do
echo "${r}
-------------------------------------------------------------
ERROR ${w}$output_dir${r} IS NOT A VALID DIRECTORY, PLEASE CHOOSE A VALID FOLDER!
-------------------------------------------------------------
"
done
fi

cd $output_dir
if [ $? -eq 0 ]
then
echo ""
else
echo "${r}
-------------------------------------------------------------------------------------------
ERROR ${w}$output_dir${r} 
IS NOT A VALID DIRECTORY, PLEASE CHOOSE A VALID FOLDER AND TRY RUN THE Seqs-Extractor AGAIN,
THIS COMMONLY OCCURS BECAUSE YOU ARE TRYING USE AND INVALID FOLDER OR A DIRECTORY THAT
CONTAINS SPACES.
${y}Example /home/lbn/teste dois/${r}
THE FOLDER NAMES CAN NOT CONTAIN SPACES, YOU CAN REPLACE SPACES BY UNDERLINE 
${y}Example /home/lbn/teste_dois/${r}
-------------------------------------------------------------------------------------------
"
function pause(){
   read -p "$*"
}
exit 1
fi

									# BLAST AND EXTRACTION 

echo    "${g}---------------------------------"
echo    "Blast search:"
echo    "---------------------------------${w}"
	echo "$BLAST"

if [ "$BLAST" != "n" ] && [ "$BLAST" != "x" ]

then
echo "${r}"
while 
read  -p 'Try again: ' BLAST && [ "$BLAST" != "n" ] && [ "$BLAST" != "x" ] ; do
echo "${r}
-------------------------------------------------------------
ERROR ${w}$BLAST${r} IS NOT A VALID OPTION, PLEASE CHOOSE A VALID OPTION!
-------------------------------------------------------------
"
done
fi

BLASTname=""
if [ $BLAST = "x" ]; then
	BLASTname="BLASTX"
fi

if [ $BLAST = "n" ]; then
	BLASTname="BLASTN"
fi

echo        "${g}---------------------------------"
echo    "Fasta to query"
	echo    "---------------------------------${w}"
	echo "${w}$query_fasta ${g}"

if [ -f $query_fasta ];
then
sleep 1
else
while 
read  -p 'Error File not found, Try again: ' query_fasta && [ ! -f $query_fasta ] ; do
echo "${r}
--------------------------------------------------------------------------
THE FILE ${w}$query_fasta${r} NOT FOUND, VERIFY IF THE NAME OR PATH TO FILE IS CORRECT!
YOU TYPED ""${w}$query_fasta${r}""
--------------------------------------------------------------------------
"
done
fi

echo        "---------------------------------"
echo    "Preformated $BLASTname database"
	echo    "---------------------------------${w}"
	echo "$BLASTdb ${g}"


if [ ! -f $BLASTdb ] ;
then
echo "${r}"
while 
read  -p 'Try again: ' BLASTdb && [ ! -f $BLASTdb ] ; do
echo "${r}
-------------------------------------------------------------
ERROR ${w}$BLASTdb${r} IS NOT A VALID OPTION, PLEASE CHOOSE A VALID OPTION!
-------------------------------------------------------------
"
done
fi
BLASTdb_name=`basename $BLASTdb`
echo    "${g}---------------------------------"
echo    "Blast E-value"
	echo    "---------------------------------${w}"
	echo "$BLAST_evalue ${g}"

if [[ -z "$BLAST_evalue" ]]
then
BLAST_evalue=1e-3
else
sleep 1
fi	

echo    "${g}---------------------------------"
echo    "CPU Threads"
	echo    "---------------------------------${w}"
echo "$threads ${g}"
if [[ -z "$threads" ]]
then
threads=`nproc`
fi

echo    "${g}---------------------------------"
echo    "$BLASTname additional parameters"
	echo    "---------------------------------${w}"
	echo "$other_blast_param ${g}"

	echo    "---------------------------------"
	echo    "Percentage of top hits to extract"
	echo    "---------------------------------${w}"
		echo "$pct_ident"


if [ "$pct_ident" != "10" ] && [ "$pct_ident" != "20" ] && [ "$pct_ident" != "30" ] && [ "$pct_ident" != "40" ] && [ "$pct_ident" != "50" ] && [ "$pct_ident" != "60" ] && [ "$pct_ident" != "70" ] && [ "$pct_ident" != "80" ] && [ "$pct_ident" != "90" ] && [ "$pct_ident" != "100" ] && [ "$pct_ident" != "10-100" ] && [ "$pct_ident" != "20-100" ] && [ "$pct_ident" != "30-100" ] && [ "$pct_ident" != "40-100" ] && [ "$pct_ident" != "50-100" ] && [ "$pct_ident" != "60-100" ] && [ "$pct_ident" != "70-100" ] && [ "$pct_ident" != "80-100" ] && [ "$pct_ident" != "90-100" ] && [ "$pct_ident" != "all" ]
			then

echo "${r}"
while 
read  -p 'Error, try again: ' pct_ident && [ "$pct_ident" != "10" ] && [ "$pct_ident" != "20" ] && [ "$pct_ident" != "30" ] && [ "$pct_ident" != "40" ] && [ "$pct_ident" != "50" ] && [ "$pct_ident" != "60" ] && [ "$pct_ident" != "70" ] && [ "$pct_ident" != "80" ] && [ "$pct_ident" != "90" ] && [ "$pct_ident" != "100" ] && [ "$pct_ident" != "10-100" ] && [ "$pct_ident" != "20-100" ] && [ "$pct_ident" != "30-100" ] && [ "$pct_ident" != "40-100" ] && [ "$pct_ident" != "50-100" ] && [ "$pct_ident" != "60-100" ] && [ "$pct_ident" != "70-100" ] && [ "$pct_ident" != "80-100" ] && [ "$pct_ident" != "90-100" ] && [ "$pct_ident" != "all" ] ; do
echo "${r}
-------------------------------------------------------------
ERROR ${w}$pct_ident${r} IS NOT A VALID OPTION, PLEASE CHOOSE A VALID OPTION!
-------------------------------------------------------------
"
done
fi
	echo    "${g}--------------------------------------------------------------------------------"
	echo	"		     Using $BLASTdb as $BLASTname database!			 "
	echo    "--------------------------------------------------------------------------------${w}"

fastafile=`basename $query_fasta`

#Replace _ by +
sed 's/_/+/g' $fastafile > .tmp

#Replace spaces by underline
sed 's/ /_/g' .tmp > .fastafile.no_spaces
rm -rf .tmp

#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
echo 	"${w}"
echo    "--------------------------------------------------------------------------------"
echo    "                                  Running $BLASTname                            "
echo    "--------------------------------------------------------------------------------"
echo 	"${w}
	------------------------------------------------------------------------
	$BLASTname options [REQUIRED]
	------------------------------------------------------------------------
	-query${g} $fastafile${w}
	-db${g} $BLASTdb ${w}
	-outfmt 6 [mandatory]

	------------------------------------------------------------------------
	Other BLAST parameters [OPTIONAL]:
	------------------------------------------------------------------------
	-E-value${g} $BLAST_evalue${w}
	-num_threads${g} $threads${w}
	$other_blast_param

	------------------------------------------------------------------------
	Extraction options
	------------------------------------------------------------------------
	Sequences with $pct_ident% of similarity will be extracted
"
if [ $BLAST = "x" ]; then
	blast_0="blastx"
	fi

if  [ $BLAST = "n" ]; then
	blast_0="blastn"
	fi
$blast_0 -version
echo    "--------------------------------------------------------------------------------"
#function of slash spin
spinner()
{
    local pid=$1
    local delay=0.75
    local spinstr='|/-\'
    while [ "$(ps a | awk '{print $1}' | grep $pid)" ]; do
        local temp=${spinstr#?}
        printf " [%c]  " "$spinstr"
        local spinstr=$temp${spinstr%"$temp"}
        sleep $delay
        printf "\b\b\b\b\b\b"
    done
    printf "    \b\b\b\b"
}

( $blast_0 -query .fastafile.no_spaces -db $BLASTdb -out $blast_0-evalue_$BLAST_evalue -evalue $BLAST_evalue -num_threads $threads -outfmt 6 $other_blast_param ) &
echo -n "Running${g} $BLASTname${w}, please wait... "
spinner $!
echo " DONE!"

#	PERCENTAGE OF IDENTITY  10 TO 100%

if [ $pct_ident = 10-100 ]
then		      
	grep -F "10." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "11." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "12." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "13." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "14." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "15." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "16." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "17." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "18." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "19." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "20." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "21." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "22." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "23." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "24." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "25." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "26." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "27." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "28." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "29." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "30." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "31." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "32." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "33." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "34." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "35." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "36." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "37." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "38." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "39." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "40." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "41." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "42." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "33." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "44." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "45." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "46." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "47." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "48." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "49." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "50." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "51." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "52." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "53." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "54." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "55." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "56." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "57." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "58." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "59." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "60." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "71." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "82." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "83." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "84." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "85." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "86." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "87." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "88." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "89." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "90." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "91." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "92." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "93." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "94." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "95." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "96." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "97." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "98." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "99." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "100." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
fi

#	PERCENTAGE OF IDENTITY  20 TO 100%
if [ $pct_ident = 20-100 ]
then	
	grep -F "20." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "21." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "22." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "23." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "24." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "25." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "26." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "27." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "28." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "29." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "30." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "31." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "32." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "33." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "34." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "35." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "36." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "37." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "38." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "39." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "40." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "41." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "42." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "33." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "44." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "45." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "46." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "47." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "48." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "49." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "50." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "51." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "52." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "53." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "54." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "55." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "56." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "57." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "58." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "59." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "60." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "71." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "82." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "83." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "84." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "85." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "86." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "87." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "88." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "89." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "90." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "91." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "92." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "93." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "94." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "95." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "96." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "97." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "98." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "99." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "100." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
fi

#	PERCENTAGE OF IDENTITY  30 TO 100%
if [ $pct_ident = 30-100 ]
then	
	grep -F "30." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "31." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "32." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "33." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "34." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "35." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "36." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "37." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "38." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "39." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "40." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "41." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "42." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "33." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "44." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "45." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "46." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "47." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "48." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "49." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "50." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "51." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "52." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "53." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "54." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "55." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "56." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "57." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "58." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "59." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "60." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "71." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "82." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "83." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "84." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "85." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "86." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "87." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "88." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "89." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "90." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "91." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "92." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "93." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "94." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "95." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "96." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "97." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "98." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "99." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "100." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
fi

#	PERCENTAGE OF IDENTITY  40 TO 100%
if [ $pct_ident = 40-100 ]
then	
	grep -F "40." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "41." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "42." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "33." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "44." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "45." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "46." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "47." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "48." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "49." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "50." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "51." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "52." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "53." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "54." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "55." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "56." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "57." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "58." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "59." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "60." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "71." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "82." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "83." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "84." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "85." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "86." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "87." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "88." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "89." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "90." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "91." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "92." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "93." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "94." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "95." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "96." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "97." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "98." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "99." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "100." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
fi

#	PERCENTAGE OF IDENTITY  50 TO 100%
if [ $pct_ident = 50-100 ]
then	
	grep -F "50." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "51." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "52." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "53." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "54." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "55." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "56." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "57." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "58." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "59." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "60." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "71." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "82." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "83." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "84." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "85." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "86." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "87." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "88." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "89." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "90." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "91." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "92." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "93." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "94." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "95." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "96." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "97." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "98." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "99." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "100." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
fi

#	PERCENTAGE OF IDENTITY  60 TO 100%
if [ $pct_ident = 60-100 ]
then	
	grep -F "60." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "71." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "82." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "83." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "84." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "85." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "86." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "87." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "88." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "89." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "90." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "91." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "92." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "93." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "94." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "95." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "96." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "97." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "98." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "99." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "100." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
fi

#	PERCENTAGE OF IDENTITY  70 TO 100%
if [ $pct_ident = 70-100 ]
then	
	grep -F "70." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "71." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "72." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "73." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "74." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "75." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "76." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "77." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "78." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "79." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "80." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "81." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "82." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "83." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "84." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "85." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "86." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "87." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "88." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "89." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "90." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "91." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "92." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "93." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "94." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "95." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "96." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "97." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "98." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "99." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "100." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
fi

#	PERCENTAGE OF IDENTITY  80 TO 100%
if [ $pct_ident = 80-100 ]
then	
	grep -F "80." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "81." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "82." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "83." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "84." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "85." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "86." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "87." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "88." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "89." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "90." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "91." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "92." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "93." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "94." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "95." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "96." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "97." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "98." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "99." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "100." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
fi

#	PERCENTAGE OF IDENTITY  90 TO 100%
if [ $pct_ident = 90-100 ]
then	
	grep -F "90." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "91." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "92." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "93." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "94." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "95." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "96." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "97." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "98." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "99." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "100." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
fi

if [ $pct_ident = 10 ]
then	
	grep -F "10." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "11." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "12." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "13." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "14." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "15." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "16." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "17." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "18." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "19." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
fi

if [ $pct_ident = 20 ]
then	
	grep -F "20." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "21." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "22." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "23." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "24." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "25." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "26." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "27." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "28." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "29." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
fi

if [ $pct_ident = 30 ]
then	
	grep -F "30." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "31." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "32." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "33." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "34." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "35." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "36." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "37." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "38." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "39." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
fi

if [ $pct_ident = 40 ]
then	
	grep -F "40." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "41." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "42." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "43." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "44." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "45." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "46." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "47." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "48." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "49." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
fi

if [ $pct_ident = 50 ]
then	
	grep -F "50." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "51." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "52." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "53." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "54." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "55." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "56." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "57." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "58." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "59." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
fi

if [ $pct_ident = 60 ]
then	
	grep -F "60." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "61." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "62." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "63." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "64." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "65." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "66." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "67." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "68." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "69." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
fi

if [ $pct_ident = 70 ]
then	
	grep -F "70." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "71." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "72." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "73." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "74." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "75." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "76." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "77." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "78." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "79." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
fi

if [ $pct_ident = 80 ]
then	
	grep -F "80." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "81." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "82." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "83." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "84." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "85." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "86." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "87." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "88." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "89." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt

fi

if [ $pct_ident = 90 ]
then	
	grep -F "90." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "91." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "92." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "93." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "94." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "95." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "96." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "97." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "98." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
	grep -F "99." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt
fi

	if [ $pct_ident = 100 ]
	then	
		grep -F "100." $blast_0-evalue_$BLAST_evalue >> .blast_res_filt

	fi

if [ $pct_ident = all ]
then	
	cp $blast_0-evalue_$BLAST_evalue .blast_res_filt
fi

#Extract only the first colum
cut -f1 .blast_res_filt > .blast_res_filt_col

#Remove duplicated IDs
sort -u .blast_res_filt_col > .blast_res_filt_col_no_dup
#add > before sequences title
sed 's/^/>/' .blast_res_filt_col_no_dup > .blast_res_filt_col_no_dup_simb

	if 
				echo "${w}"
				echo    "--------------------------------------------------------------------------------"
				echo	"Extracting sequences, just wait.			 "
				echo 	"This may take a while and depends on the size of your database. 	 "
				echo    "--------------------------------------------------------------------------------"
				echo	""
#function of slash spin
spinner()
{
    local pid=$1
    local delay=0.75
    local spinstr='|/-\'
    while [ "$(ps a | awk '{print $1}' | grep $pid)" ]; do
        local temp=${spinstr#?}
        printf " [%c]  " "$spinstr"
        local spinstr=$temp${spinstr%"$temp"}
        sleep $delay
        printf "\b\b\b\b\b\b"
    done
    printf "    \b\b\b\b"
}

( cut -c 2- .blast_res_filt_col_no_dup_simb | xargs -n 1 samtools faidx .fastafile.no_spaces > .seqs_only_the_tophit_tmp ) &
echo -n "Running SAMTOOLS, please wait... "
spinner $!
echo " DONE!"
rm -rf .blast_res_filt_col_no_dup_simb

#Replace underline by spaces
sed 's/_/ /g' .seqs_only_the_tophit_tmp > .seqs_only_the_tophit_spaces
rm -rf .seqs_only_the_tophit_tmp
sed 's/+/_/g' .seqs_only_the_tophit_spaces > seqs_only_the_tophit_$pct_ident%.fasta
rm -rf .seqs_only_the_tophit_spaces

sed 's/_/ /g' .blast_res_filt > .blast_res_filt_nspaces
rm -rf .blast_res_filt
sed 's/+/_/g' .blast_res_filt_nspaces > list_of_tophit-$pct_ident%_and_$blast_0-results
rm -rf .blast_res_filt_nspaces
sed 's/+/_/g' $blast_0-evalue_$BLAST_evalue > .blast-evalue
rm -rf $blast_0-evalue_$BLAST_evalue
cat .blast-evalue > $blast_0-evalue_$BLAST_evalue
rm -rf .blast-evalue

#Clean temporary files
rm -rf .blast_res_filt_col .blast_res_filt_col_no_dup .blast_res_filt_nspaces .fastafile.no_spaces.fai .fastafile.no_spaces

then 
echo 	"${w}"
echo    "--------------------------------------------------------------------------------"
echo	"		 	 Sequences successfully extracted!!!			 "
echo    "--------------------------------------------------------------------------------"
	else
		echo -e "setf 4" | tput -S  # set fg red
		echo	"ERROR!"
		echo	"PLEASE VERIFY IF THE COMMANDS AND NAME OF fiLES ARE CORRECT!!!!"
function pause(){
   read -p "$*"
}
echo -e "setf 4" | tput -S
pause 'Press [Enter] key to finish the script'		
exit 1
	fi

if [ -s seqs_only_the_tophit_$pct_ident%.fasta ]
then

echo 	"${g}"
echo	"===================================================================================================="
echo 	""
echo    "======================================== SeqsExtractor ============================================="
echo 	""
echo	"===================================================================================================="
echo    "======================= Laboratório de Biologia Molecular e Neuroecologia =========================="
echo	'=======================  INSTITUTO FEDERAL DO PARÁ (IFPA) Campus Bragança =========================='
echo	"===================================================================================================="
echo '				         ___        ______    __     __
                                        |   |      |      \  |  \   |  | 
                                        |   |      |   D   ) |   \  |  | 
                                        |   |      |      /  |    \ |  | 
                                        |   |____  |      \  |  |\ \|  | 
                                        |        | |   D   ) |  | \    |  
                                        |________| |______/  |__|  \___|
'                   
echo	"All commands completed successfully"
echo	":D"
echo	"Support by E-mail:${w} patrick@ufpa.br${g}"
echo	""
echo    "-----------------------------------------------------------------------------------------------------"
echo	"The extracted sequences are written in${w} seqs_only_the_tophit_$pct_ident%.fasta${g}"
echo	"The${w} $BLASTname${g} results are written in${w} $blast_0-results_evalue_$BLAST_evalue.outfmt6 ${g} "
echo	"The file${w} list_of_tophit-$pct_ident%_and_$blast_0-results${g} contain the $BLASTname results only for${w} $pct_ident% ${g}of similarity"
echo	"The files of $BLASTname database are available in ${w}$output_dir${g}"
echo	"${y}NOTE: Results will be available at${w} $output_dir${g}"
echo    "-----------------------------------------------------------------------------------------------------"
echo    "User manual on SeqsExtractor wiki:${w} https://github.com/patrick-douglas/Seqs-Extractor/wiki ${g}"
echo    "-----------------------------------------------------------------------------------------------------"

else
     		echo "${r}"
	echo    "-------------------------------------------------------------------------------------------
"
	echo	"No sequences with $pct_ident% was found, please try again by changing your search criteria!
"
	echo	"${g}You can access the $blast_0 results in $blast_0-results_evalue_$BLAST_evalue.outfmt6"
	echo    "${r}-------------------------------------------------------------------------------------------"
	echo	""
rm -rf seqs_only_the_tophit_$pct_ident%.fasta
rm -rf list_of_tophit-$pct_ident%_and_$blast_0-results $blast_0-evalue_$BLAST_evalue
fi
