#!/bin/bash
w=$(tput sgr0) 
r=$(tput setaf 1)
g=$(tput setaf 2) 
y=$(tput setaf 3) 

while getopts "d" opt; do
    case "$opt" in
    h|\?)
echo ''
        ;;
d)  
	echo	"${g}_________________________________________________________________________________________________________"
	echo 	""
	echo    "				            Seqs-Extractor"
	echo	"_________________________________________________________________________________________________________"
	echo 	""
	echo    "---------------------------------------------------------------------------------------------------------${w}"
wget https://ufpr.dl.sourceforge.net/project/seqs-extractor/example_files/example_files.tar.gz --directory-prefix=example_files/
	echo    "${g}---------------------------------------------------------------------------------------------------------"



        ;;
esac
done
if [ "$d" = "" ]; then
echo "${g}"
	echo "${g}"
	echo	"_________________________________________________________________________________________________________"
	echo 	""
	echo    "				            Seqs-Extractor"
	echo	"_________________________________________________________________________________________________________"
	echo 	""
	echo    "---------------------------------------------------------------------------------------------------------"
	echo    "USAGE EXAMPLE:"
    echo    "${w}SeqsExtractor-extract-de-trinity -i <Trinity.fasta> -d <trinity.de.folder> -o <output-directory>"
	echo    "${g}---------------------------------------------------------------------------------------------------------"
	echo ""
	echo "${w} SeqsExtractor-blast-and-extract${g}   | perform extraction and BLAST"
	echo "${w} SeqsExtractor-extract-from-blast${g}  | perform extraction without (BLAST outfmt6 file required)"
	echo "${w} SeqsExtractor-extract-from-misa${g}   | perform extraction using MISA file"
	echo "${w} SeqsExtractor-run-misa-and-extract${g}| run MISA and perform extraction of sequences"
	echo "${w} SeqsExtractor-customize-misa${g}      | customize${w} misa.ini${g} file (Please see the README.md)"
	echo "${w} SeqsExtractor-extract-using-txt${g}   | extract using any text file (Please see the README.md)"
	echo "${w} SeqsExtractor-extract-de-trinity${g}  | extract sequences from Trinity DE folder (Please see the README.md))"
	echo "${w} SeqsExtractor -d               ${g}   | download ${w} Example files${g} from SeqsExtractor SF repository"
    echo	""
	echo 	"---------------------------------------------------------------------------------------------------------${w}"
	echo	" Complete user manual ${w}https://github.com/patrick-douglas/Seqs-Extractor/wiki${g}"
	echo 	"---------------------------------------------------------------------------------------------------------"
exit 1
fi

