#!/bin/bash
w=$(tput sgr0) 
r=$(tput setaf 1)
g=$(tput setaf 2) 
y=$(tput setaf 3) 
S=`basename $0`
cpu=`nproc`
USAGE=`echo "USAGE:
${g}Example:${w} $S -i query.fa -l list_of_seqs.txt -o /home/user/test

Required arguments: 
-i <string> | Query fasta
-l <string> | List of sequences 
-o <string> | Output directory
Optional arguments:
-a <y or n> | Keep additional info in the seqs ID (Default n)"`

if [ "$#" -lt "3" ] 
then 
    echo $USAGE;
exit 1    
else 
    var1=$2;
    var2=$4;
fi

while getopts i:l:o:a: option
do
case "${option}"
in
i) fasta=${OPTARG};;
l) list_file_path=$OPTARG;;
o) output_dir=$OPTARG;;
a) keep_add_info=$OPTARG;;
esac
done
if [ "$fasta" = "" ]; then
"${g}Error, missing arguments:${y} -i | Query fasta | <string>
${w}$USAGE"
exit 1
fi
if [ "$list_file_path" = "" ]; then
"${g}Error, missing arguments:${y} -l | List of sequences | <string>
${w}$USAGE"
exit 1
fi
if [ "$output_dir" = "" ]; then
"${g}Error, missing arguments:${y} -o | Output directory for extracted seqs | <string>
${w}$USAGE"
exit 1
fi
	echo "${g}"
	echo	"________________________________________________________________________________"
	echo 	""
	echo    "_______________________________ SeqsExtractor __________________________________"
	echo	"________________________________________________________________________________"
	echo	""
echo    "${g}---------------------------------"
echo    "Query Fasta:"
echo    "---------------------------------${w}"
	echo "$fasta"

if [ -f $fasta ];
then
sleep 1
else
echo "${r}
--------------------------------------------------------------------------
THE FILE ${w}$fasta${r} WAS NOT FOUND, VERIFY IF THE NAME OR PATH TO FILE IS CORRECT!
--------------------------------------------------------------------------"
exit 1
fi


echo    "${g}---------------------------------"
echo    "List of seqs:"
echo    "---------------------------------${w}"
	echo "$list_file_path"
if [ -f $list_file_path ];
then
sleep 1
else
echo "${r}
--------------------------------------------------------------------------
THE FILE ${w}$list_file_path${r} WAS NOT FOUND, VERIFY IF THE NAME OR PATH TO FILE IS CORRECT!
--------------------------------------------------------------------------"
exit 1
fi
	echo "${g}"
	echo    "---------------------------------"
	echo    "Output directory"
	echo    "---------------------------------${w}"
echo "$output_dir ${g}"
cd $output_dir

if [ "$keep_add_info" = "y" ]; then
keep_addtional=Yes
else
keep_addtional=No
echo "" 
fi


	echo "${g}"
	echo    "---------------------------------"
	echo    "Keep addtional info in the seq IDs?"
	echo    "---------------------------------${w}"
echo "$keep_addtional ${g}"

if [ $? -eq 0 ]
then
echo ""
else
echo "${r}
-------------------------------------------------------------------------------------------
ERROR ${w}$output_dir${r} 
IS NOT A VALID DIRECTORY, PLEASE CHOOSE A VALID FOLDER AND TRY RUN THE Seqs-Extractor AGAIN,
THIS COMMONLY OCCURS BECAUSE YOU ARE TRYING USE AND INVALID FOLDER OR A DIRECTORY THAT
CONTAINS SPACES.
${y}Example /home/lbn/teste dois/${r}
THE FOLDER NAMES CAN NOT CONTAIN SPACES, YOU CAN REPLACE SPACES BY UNDERLINE 
${y}Example /home/lbn/teste_dois/${r}
-------------------------------------------------------------------------------------------
"
function pause(){
   read -p "$*"
}
exit 1
fi


		if 
				if			
				echo "${w}"
				echo    "--------------------------------------------------------------------------------"
				echo	"Extracting sequences, just wait.			 "
				echo 	"This may take a while and depends of database size. 	 "
				echo    "--------------------------------------------------------------------------------"

				echo	""
#Change the entire path to only last name
list_file=`basename $list_file_path`
#Change the entire path to only last name
fastaname=`basename $fasta`

if [ "$keep_add_info" = "" ]; then
echo ""
elif [ "$keep_add_info" = "n" ]; then
echo ""
else
#Replace spaces by +
sed -e 's/\s\+/*/g' $list_file_path > .list.file.path.no.spaces
sed -e 's/\s\+/*/g' $fasta > .fasta.no.spaces
list_file_path=.list.file.path.no.spaces
fasta=.fasta.no.spaces
fi

#function of slash spin
spinner()
{
    local pid=$1
    local delay=0.75
    local spinstr='|/-\'
    while [ "$(ps a | awk '{print $1}' | grep $pid)" ]; do
        local temp=${spinstr#?}
        printf " [%c]  " "$spinstr"
        local spinstr=$temp${spinstr%"$temp"}
        sleep $delay
        printf "\b\b\b\b\b\b"
    done
    printf "    \b\b\b\b"
}
( cut -c 2- $list_file_path | xargs -n 1 samtools faidx $fasta > $fastaname.$list_file.ext_seqs.fa ) &
echo -n "Running SAMTOOLS, please wait... "
spinner $!
echo " DONE!"
sed -i -e 's/*\+/ /g' $fastaname.$list_file.ext_seqs.fa
					then
						echo " "
					else
						echo -e "setf 4" | tput -S  # set fg red
						echo	"ERROR!"
						echo	"PLEASE VERIFY IF THE COMMANDS AND NAME OF fiLES ARE CORRECT!!!!"
						function pause(){
						read -p "$*"
						}
						echo -e "setf 4" | tput -S
						pause 'Press [Enter] key to finish the script'
						exit 1
					fi
			then 
				echo "${g}"
				echo    "--------------------------------------------------------------------------------"
				echo	"		 	 Sequences successfully extracted!!!			 "
				echo    "--------------------------------------------------------------------------------"
				echo	""
rm -rf $fasta.fai .list.file.path.no.spaces .fasta.no.spaces
		fi			
rm -rf $fasta.fai .list.file.path.no.spaces .fasta.no.spaces


if [ -s $fastaname.$list_file.ext_seqs.fa ] 
then


    
echo -e "setf 8" | tput -S  # set fg green
echo	"================================================================================"
echo 	""
echo    "============================ Seqs-Extractor 1.1 ================================"
echo 	""
echo	"================================================================================"
echo    "============= Laboratório de Biologia Molecular e Neuroecologia ================"
echo	'============== INSTITUTO FEDERAL DO PARÁ (IFPA) Campus Bragança ================'
echo	"================================================================================"
echo '				 ___        ______    __     __
				|   |      |	  \  |  \   |  | 
				|   |      |   D   ) |   \  |  | 
				|   |      |      /  |    \ |  | 
				|   |____  |      \  |  |\ \|  | 
				|        | |   D   ) |  | \    |  
				|________| |______/  |__|  \___|
'                     
echo	"All commands completed successfully"
echo	":D"
echo	"Support by E-mail to patrick@ufpa.br"
echo	""
echo    "--------------------------------------------------------------------------------"
echo	"The extracted sequences are written in${w} $fastaname.$list_file.fa${g}"    
echo    "${y}NOTE: Results are available at${w} $selected_dir${g}"
echo    "--------------------------------------------------------------------------------"
else
     		echo "${r}"
	echo    "-------------------------------------------------------------------------------------------
"
	echo	"No sequences was found, please try again by changing your search criteria!
	"
	echo    "-------------------------------------------------------------------------------------------"
	echo	""
rm -f $list_file_name.$fastafile_name.extracted_seqs.fasta .$fastafile_name.fai

fi
