#!/bin/bash
textreset=$(tput sgr0) 
red=$(tput setaf 1)
green=$(tput setaf 2) 
orange=$(tput setaf 8) 
	echo "${green}"
	echo	"________________________________________________________________________________"
	echo 	""
	echo    "_________________________ BLAST Extractor 2.9 [BETA] ___________________________"
	echo	"________________________________________________________________________________"
	echo	""
	echo "${textreset}"
	echo    "--------------------------------------------------------------------------------"
	echo    "                         Configuration script                             "
	echo    "--------------------------------------------------------------------------------"
		echo ""
	echo "Do you want add BLAST Extractor icon in the destop?

${green} 1${textreset} Yes 
${green} 2${textreset} No"

		echo "${green}"
		read desktop_opt
		echo "${textreset}"

if [ "$desktop_opt" != "1" ] && [ "$desktop_opt" != "2" ]
then
echo "${red}"
while 
read -p 'Try again: ' desktop_opt && [ "$desktop_opt" != "1" ] && [ "$desktop_opt" != "2" ] ; do
echo "${red}
-------------------------------------------------------------
ERROR ${textreset}$desktop_opt${red} IS NOT A VALID OPTION, PLEASE CHOOSE A VALID OPTION!
-------------------------------------------------------------
"
done
fi

if [ $desktop_opt = "1" ]; then
cp /usr/share/applications/BLAST-Extractor.desktop ~/Desktop
fi
